owner: viespirkiu-grupe
repo: status

sites:
  - name: Viešpirkiai
    icon: https://viespirkiai.top/icons/icon.png
    url: https://viespirkiai.top
    type: globalping
    location: Lithuania
  - name: Failai
    icon: https://viespirkiai.top/icons/icon.png
    url: https://failai.viespirkiai.top
    type: globalping
    location: Lithuania
  - name: Dokumentų nuskaitytojas (RDP)
    icon: https://images.emojiterra.com/google/noto-emoji/unicode-16.0/color/1024px/1f4d1.png
    url: $RDP
    port: 80
    check: tcp-ping
  - name: Dokumentų nuskaitytojas (RFC)
    icon: https://images.emojiterra.com/google/noto-emoji/unicode-16.0/color/1024px/1f4d1.png
    url: $RFC
    port: 9120
    check: tcp-ping
  - name: Dokumentų nuskaitytojas (MŠK)
    icon: https://images.emojiterra.com/google/noto-emoji/unicode-16.0/color/1024px/1f4d1.png
    url: https://skaitytojas.poci.us
    port: 443
    check: tcp-ping
  - name: CVPP
    url: https://cvpp.eviesiejipirkimai.lt
    type: globalping
    location: Lithuania
  - name: CVP IS
    url: https://viesiejipirkimai.lt
    type: globalping
    location: Lithuania
  - name: CVP IS (sena-1)
    icon: https://eviesiejipirkimai.lt/templates/vpt/cvpp_files/favicon0.png
    url: https://eviesiejipirkimai.lt
    type: globalping
    location: Lithuania+eyeball # residential IP
  - name: CVP IS (sena-2)
    url: https://pirkimai.eviesiejipirkimai.lt
    type: globalping
    location: Lithuania
  - name: VPT
    icon: https://vpt.lrv.lt/static/favicon/apple-touch-icon.1cbee2523114.png
    url: https://vpt.lrv.lt
    type: globalping
    location: Lithuania
  - name: TED
    url: https://ted.europa.eu
    type: globalping
    location: Lithuania

status-website:
  cname: status.viespirkiai.top
  logoUrl: https://viespirkiai.top/icons/icon.png
  name: Viešpirkiai Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Viešpirkiai
      href: https://viespirkiai.top
