owner: viespirkiu-grupe
repo: status

sites:
  - name: Viešpirkiai
    url: https://viespirkiai.top

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Viešpirkiai
      href: https://viespirkiai.top
