owner: viespirkiu-grupe
repo: status

sites:
  - name: Viešpirkiai
    url: https://viespirkiai.top

status-website:
  cname: status.viespirkiai.top
  logoUrl: https://viespirkiai.top/icons/icon.png
  name: Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Viešpirkiai
      href: https://viespirkiai.top
